// Code generated by "stringer -type=PortState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Open-0]
	_ = x[Closed-1]
	_ = x[Filtered-2]
	_ = x[Unreachable-3]
}

const _PortState_name = "OpenClosedFilteredUnreachable"

var _PortState_index = [...]uint8{0, 4, 10, 18, 29}

func (i PortState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PortState_index)-1 {
		return "PortState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PortState_name[_PortState_index[idx]:_PortState_index[idx+1]]
}
